//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace z_mes_mm_material_transport_02
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="z_mes_mm_material_transport_02.Z_MES_MM_MATERIAL_TRANSPORT_02")]
    public interface Z_MES_MM_MATERIAL_TRANSPORT_02
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:Z_MES_MM_MATERIAL_TRANSPORT_02:Z" +
            "MesMmMaterialTransport02Request", ReplyAction="urn:sap-com:document:sap:soap:functions:mc-style:Z_MES_MM_MATERIAL_TRANSPORT_02:Z" +
            "MesMmMaterialTransport02Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<z_mes_mm_material_transport_02.ZMesMmMaterialTransport02Response1> ZMesMmMaterialTransport02Async(z_mes_mm_material_transport_02.ZMesMmMaterialTransport02Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZMesMmMaterialTransport02
    {
        
        private ZmatnrTranH headerField;
        
        private ZmatnrTranI[] itemtableField;
        
        private string mesKeyField;
        
        private ZmesMsgStru[] msgtabField;
        
        private string pLanguField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZmatnrTranH Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZmatnrTranI[] Itemtable
        {
            get
            {
                return this.itemtableField;
            }
            set
            {
                this.itemtableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MesKey
        {
            get
            {
                return this.mesKeyField;
            }
            set
            {
                this.mesKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZmesMsgStru[] Msgtab
        {
            get
            {
                return this.msgtabField;
            }
            set
            {
                this.msgtabField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PLangu
        {
            get
            {
                return this.pLanguField;
            }
            set
            {
                this.pLanguField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmatnrTranH
    {
        
        private string pstngDateField;
        
        private string docDateField;
        
        private string refDocNoField;
        
        private string billOfLadingField;
        
        private string grGiSlipNoField;
        
        private string headerTxtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PstngDate
        {
            get
            {
                return this.pstngDateField;
            }
            set
            {
                this.pstngDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DocDate
        {
            get
            {
                return this.docDateField;
            }
            set
            {
                this.docDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string RefDocNo
        {
            get
            {
                return this.refDocNoField;
            }
            set
            {
                this.refDocNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BillOfLading
        {
            get
            {
                return this.billOfLadingField;
            }
            set
            {
                this.billOfLadingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string GrGiSlipNo
        {
            get
            {
                return this.grGiSlipNoField;
            }
            set
            {
                this.grGiSlipNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string HeaderTxt
        {
            get
            {
                return this.headerTxtField;
            }
            set
            {
                this.headerTxtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmesMatdocStru
    {
        
        private string matDocField;
        
        private string docYearField;
        
        private string mesKeyField;
        
        private string rangeNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MatDoc
        {
            get
            {
                return this.matDocField;
            }
            set
            {
                this.matDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DocYear
        {
            get
            {
                return this.docYearField;
            }
            set
            {
                this.docYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MesKey
        {
            get
            {
                return this.mesKeyField;
            }
            set
            {
                this.mesKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string RangeNum
        {
            get
            {
                return this.rangeNumField;
            }
            set
            {
                this.rangeNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmesMsgStru
    {
        
        private string typeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmatnrTranI
    {
        
        private string materialField;
        
        private string plantField;
        
        private string fromLocField;
        
        private string fromBatchField;
        
        private string moveTypeField;
        
        private string specStockField;
        
        private string vendorField;
        
        private string salesOrdField;
        
        private string sOrdItemField;
        
        private decimal entryQntField;
        
        private string entryUomField;
        
        private string entryUomIsoField;
        
        private string poNumberField;
        
        private string poItemField;
        
        private string itemTextField;
        
        private string grRcptField;
        
        private string costcenterField;
        
        private string orderidField;
        
        private string orderItnoField;
        
        private string toMatnrField;
        
        private string toPlantField;
        
        private string toStlocField;
        
        private string toBatchField;
        
        private string moveReasField;
        
        private string refDocYrField;
        
        private string refDocField;
        
        private string refDocItField;
        
        private string toSalesOrdField;
        
        private string toSOrdItemField;
        
        private string reservNoField;
        
        private string resItemField;
        
        private string zflag2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Material
        {
            get
            {
                return this.materialField;
            }
            set
            {
                this.materialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Plant
        {
            get
            {
                return this.plantField;
            }
            set
            {
                this.plantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string FromLoc
        {
            get
            {
                return this.fromLocField;
            }
            set
            {
                this.fromLocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string FromBatch
        {
            get
            {
                return this.fromBatchField;
            }
            set
            {
                this.fromBatchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MoveType
        {
            get
            {
                return this.moveTypeField;
            }
            set
            {
                this.moveTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SpecStock
        {
            get
            {
                return this.specStockField;
            }
            set
            {
                this.specStockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Vendor
        {
            get
            {
                return this.vendorField;
            }
            set
            {
                this.vendorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string SalesOrd
        {
            get
            {
                return this.salesOrdField;
            }
            set
            {
                this.salesOrdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SOrdItem
        {
            get
            {
                return this.sOrdItemField;
            }
            set
            {
                this.sOrdItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal EntryQnt
        {
            get
            {
                return this.entryQntField;
            }
            set
            {
                this.entryQntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string EntryUom
        {
            get
            {
                return this.entryUomField;
            }
            set
            {
                this.entryUomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string EntryUomIso
        {
            get
            {
                return this.entryUomIsoField;
            }
            set
            {
                this.entryUomIsoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string PoNumber
        {
            get
            {
                return this.poNumberField;
            }
            set
            {
                this.poNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string PoItem
        {
            get
            {
                return this.poItemField;
            }
            set
            {
                this.poItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string ItemText
        {
            get
            {
                return this.itemTextField;
            }
            set
            {
                this.itemTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string GrRcpt
        {
            get
            {
                return this.grRcptField;
            }
            set
            {
                this.grRcptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Costcenter
        {
            get
            {
                return this.costcenterField;
            }
            set
            {
                this.costcenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Orderid
        {
            get
            {
                return this.orderidField;
            }
            set
            {
                this.orderidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string OrderItno
        {
            get
            {
                return this.orderItnoField;
            }
            set
            {
                this.orderItnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string ToMatnr
        {
            get
            {
                return this.toMatnrField;
            }
            set
            {
                this.toMatnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string ToPlant
        {
            get
            {
                return this.toPlantField;
            }
            set
            {
                this.toPlantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string ToStloc
        {
            get
            {
                return this.toStlocField;
            }
            set
            {
                this.toStlocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string ToBatch
        {
            get
            {
                return this.toBatchField;
            }
            set
            {
                this.toBatchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string MoveReas
        {
            get
            {
                return this.moveReasField;
            }
            set
            {
                this.moveReasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string RefDocYr
        {
            get
            {
                return this.refDocYrField;
            }
            set
            {
                this.refDocYrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string RefDoc
        {
            get
            {
                return this.refDocField;
            }
            set
            {
                this.refDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string RefDocIt
        {
            get
            {
                return this.refDocItField;
            }
            set
            {
                this.refDocItField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string ToSalesOrd
        {
            get
            {
                return this.toSalesOrdField;
            }
            set
            {
                this.toSalesOrdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string ToSOrdItem
        {
            get
            {
                return this.toSOrdItemField;
            }
            set
            {
                this.toSOrdItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string ReservNo
        {
            get
            {
                return this.reservNoField;
            }
            set
            {
                this.reservNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string ResItem
        {
            get
            {
                return this.resItemField;
            }
            set
            {
                this.resItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string Zflag2
        {
            get
            {
                return this.zflag2Field;
            }
            set
            {
                this.zflag2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZMesMmMaterialTransport02Response
    {
        
        private ZmatnrTranI[] itemtableField;
        
        private ZmesMatdocStru matDocInfoField;
        
        private ZmesMsgStru[] msgtabField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZmatnrTranI[] Itemtable
        {
            get
            {
                return this.itemtableField;
            }
            set
            {
                this.itemtableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ZmesMatdocStru MatDocInfo
        {
            get
            {
                return this.matDocInfoField;
            }
            set
            {
                this.matDocInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZmesMsgStru[] Msgtab
        {
            get
            {
                return this.msgtabField;
            }
            set
            {
                this.msgtabField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZMesMmMaterialTransport02Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public z_mes_mm_material_transport_02.ZMesMmMaterialTransport02 ZMesMmMaterialTransport02;
        
        public ZMesMmMaterialTransport02Request()
        {
        }
        
        public ZMesMmMaterialTransport02Request(z_mes_mm_material_transport_02.ZMesMmMaterialTransport02 ZMesMmMaterialTransport02)
        {
            this.ZMesMmMaterialTransport02 = ZMesMmMaterialTransport02;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZMesMmMaterialTransport02Response1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public z_mes_mm_material_transport_02.ZMesMmMaterialTransport02Response ZMesMmMaterialTransport02Response;
        
        public ZMesMmMaterialTransport02Response1()
        {
        }
        
        public ZMesMmMaterialTransport02Response1(z_mes_mm_material_transport_02.ZMesMmMaterialTransport02Response ZMesMmMaterialTransport02Response)
        {
            this.ZMesMmMaterialTransport02Response = ZMesMmMaterialTransport02Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface Z_MES_MM_MATERIAL_TRANSPORT_02Channel : z_mes_mm_material_transport_02.Z_MES_MM_MATERIAL_TRANSPORT_02, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Z_MES_MM_MATERIAL_TRANSPORT_02Client : System.ServiceModel.ClientBase<z_mes_mm_material_transport_02.Z_MES_MM_MATERIAL_TRANSPORT_02>, z_mes_mm_material_transport_02.Z_MES_MM_MATERIAL_TRANSPORT_02
    {
        
        public Z_MES_MM_MATERIAL_TRANSPORT_02Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<z_mes_mm_material_transport_02.ZMesMmMaterialTransport02Response1> z_mes_mm_material_transport_02.Z_MES_MM_MATERIAL_TRANSPORT_02.ZMesMmMaterialTransport02Async(z_mes_mm_material_transport_02.ZMesMmMaterialTransport02Request request)
        {
            return base.Channel.ZMesMmMaterialTransport02Async(request);
        }
        
        public System.Threading.Tasks.Task<z_mes_mm_material_transport_02.ZMesMmMaterialTransport02Response1> ZMesMmMaterialTransport02Async(z_mes_mm_material_transport_02.ZMesMmMaterialTransport02 ZMesMmMaterialTransport02)
        {
            z_mes_mm_material_transport_02.ZMesMmMaterialTransport02Request inValue = new z_mes_mm_material_transport_02.ZMesMmMaterialTransport02Request();
            inValue.ZMesMmMaterialTransport02 = ZMesMmMaterialTransport02;
            return ((z_mes_mm_material_transport_02.Z_MES_MM_MATERIAL_TRANSPORT_02)(this)).ZMesMmMaterialTransport02Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
